name: publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“š checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.8.0
          run_install: |
            - recursive: true
      - name: ðŸŸ¢ node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - name: Create Release
        id: release
        uses: halvardssm/github-action-tag-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./package.json # optional, will use ./package.json by default
      - run: |
          echo 'Release created: ${{steps.version.outputs.release_created}}' # 'true' or 'false'
          echo 'Release exists: ${{steps.version.outputs.release_exists}}' # 'true' or 'false'
          echo 'Release tag: ${{steps.version.outputs.release_tag}}' # The tag from package.json
      - if: ${{steps.release.outputs.release_exists == 'true'}}
        run: echo "Release already exists"
      - name: Publish package on NPM ðŸ“¦
        run: npm publish --scope=kiwilan --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
